data_dictionary = {
    "npc": [
        "Aegis",
        "Aegeon",
        "Abyssal",
        "Aegean",
        "Aeos",
        "Aesop",
        "Agatha",
        "Alexander",
        "Ambrosia",
        "Anastas",
        "Anatol",
        "Anaxis",
        "Anthea",
        "Anti",
        "Aqua",
        "Ares",
        "Astra",
        "Athena",
        "Atlas",
        "Atticus",
        "Aurora",
        "Azalea",
        "Blasto",
        "Barbar",
        "Cambrian",
        "Ceos",
        "Chromos",
        "Chrysanthe",
        "Clara",
        "Corfu",
        "Crete",
        "Demeter",
        "Dendra",
        "Diatom",
        "Dimitar",
        "Ephesus",
        "Ektos",
        "Euclid",
        "Europa",
        "Florina",
        "Galen",
        "Geo",
        "Giga",
        "Gregory",
        "Hadrian",
        "Helios",
        "Hellena",
        "Hera",
        "Hero",
        "Hippo",
        "Ichthys",
        "Iliad",
        "Ion",
        "Ithaca",
        "Jocasta",
        "Kalamata",
        "Karnak",
        "Kilo",
        "Knossos",
        "Kyntho",
        "Kythera",
        "Larissa",
        "Leonidas",
        "Linus",
        "Macedon",
        "Macro",
        "Mega",
        "Meta",
        "Meteora",
        "Mykonos",
        "Nausica",
        "Nautilus",
        "Paleos",
        "Panthalassa",
        "Papyr",
        "Parthas",
        "Patina",
        "Patras",
        "Patricia",
        "Petar",
        "Philo",
        "Phono",
        "Photon",
        "Phyto",
        "Pliny",
        "Polis",
        "Pyre",
        "Pyro",
        "Rhodes",
        "Santorini",
        "Seneca",
        "Sophia",
        "Syracuse",
        "Tauro",
        "Telemakhos",
        "Tethys",
        "Thrace",
        "Volos",
        "Vulcan",
        "Xylo",
        "Tipmast",
        "Tiderace",
        "Sparwood",
        "Hullman",
        "Stemman",
        "Beacher",
        "Pullerman",
        "Bluewater",
        "Shearwater",
        "Runningwake",
        "Boardalee",
        "Seabelt",
        "Laertes",
        "Ahkaia",
        "Seareach",
        "Phaikian",
        "Eurymas",
        "Kyklops",
        "Sparta",
        "Theo",
        "Aiolia",
        "Kirke",
        "Perses",
        "Koral",
        "Hortos",
        "Mariner",
        "Tyro",
        "Khloris",
        "Neleos",
        "Ampheon",
        "Iasos",
        "Iphikos",
        "Ledâ",
        "Kastor",
        "Ariadne",
        "Phaidra",
        "Priam",
        "Kassandra",
        "Penelope",
        "Alkinous",
        "Circe",
        "Atalanta",
        "Caledonia",
        "Troy",
        "Eumaious",
        "Maia",
        "Cyros",
        "Akastios",
        "Thaos",
        "Nestor",
        "Starlight",
        "Logia",
        "Eurymakhos",
        "Stratos",
        "Hellas",
        "Atreos",
        "Meneláo",
        "Ortílikhos",
        "Alpheios",
        "Pylos",
        "Ikarios",
        "Dawn",
        "Anemone",
        "Rose",
        "Hyacinth",
        "Eurykleia",
        "Lydia",
        "Phrygia",
        "Ionia",
        "Aeolia",
        "Terra",
        "Marina",
        "Seiya",
        "Serene",
        "Phia",
        "Leta",
        "Calliope",
        "Acacia",
        "Demi",
        "Gaia",
        "Rhea",
        "Myrtle",
        "Xenia",
        "Koralia",
        "Pelagia",
        "Theodesia",
        "Esphion",
        "Iconos",
        "Icthya",
        "Delfina",
        "Nymph",
        "Chiron",
        "Ephimera",
        "Pithikohs",
        "Cadmus",
        "Spartoi",
        "Jason",
        "Phoenicia",
        "Medea",
        "Ekion"
    ],
    "npc_weights" : [33,33,33,1],
    "tribe": ["Ionian", "Phrygian", "Aeolian", "Xenoi"],
    "personality": [
        "Shy",
        "Grumpy",
        "Serious",
        "Outgoing",
        "Nervous",
        "Silly",
        "Calm",
        "Curious",
        "Child-like",
        "Aloof",
        "Melancholic",
        "Roll for two personalities"
    ],
    "voice": [
        "Ordinary",
        "Ordinary",
        "Ordinary",
        "Ordinary",
        "Ordinary",
        "Ordinary",
        "Ordinary",
        "Ordinary",
        "Ordinary",
        "Ordinary",
        "Lisp",
        "Big and Boomy",
        "Aspirated",
        "Falsetto",
        "Gruff and Gravely",
        "Child-like",
        "Surfer",
        "Valley",
        "Cockney",
        "Sultry",
        "King Krule / Zoo Kid",
        "Austrian Muscleman",
        "Australian",
        "Mario TV show",
        "Luigi TV show",
        "Jacques Cousteau",
        "Northeastern Urbanite",
        "Movie Trailer Narrator",
        "Signing",
        "Nasal",
        "Queer-coded",
        "f",
        "d",
        "Scandinavian",
        "Old New England",
        "Soviet Friend Yuri",
        "Lowland Southern Accent",
        "Barackus Obabo",
        "Louie Armstrong",
        "Spoiled Child"
    ],
    "speech": [
        "Homeric",
        "Sea Dog",
        "Shakespearean",
        "Simple",
        "Neolithic",
        "Inverted",
        "Casual",
        "Disjointed",
        "Poetic",
        "Dry"
    ],
    "catchphrase": ["Huzzah", "Woah"],
    "quirks": [
        "Chromatic",
        "Skeptical",
        "Gullible",
        "Talks really fast",
        "Talks very slow",
        "Examines people’s faces up close when speaking",
        "Speaks with interrogative inflections",
        "Exaggerated hand movements",
        "Always sarcastic",
        "Always apologizes",
        "Always has their weapon drawn",
        "Has strong body odor",
        "Smells of great perfume",
        "Sings everything",
        "Strikes poses to accentuate speech",
        "Frightened easily and often",
        "Inferiority complex",
        "Superiority complex",
        "Flirty, looking for love",
        "Tender and parently with others",
        "Emotionless",
        "Hand puppets",
        "Fatigued",
        "Vengeful",
        "Forgiving",
        "Nothing noteworthy"
    ],
    "appearance": [
        "Distinct facial feature",
        "Grey-eyed",
        "Constantly has snot hanging",
        "Super lanky",
        "Super swole",
        "Stunning Hair/Plumage/Fins",
        "Dark plumage/scales/skin tone",
        "Lazy eyes",
        "Short",
        "Tall",
        "Wide jaw/large beak",
        "Gap tooth/Cracked beak",
        "Is covered in scars",
        "Has many tattoos",
        "Has tired sunken-in eyes",
        "Bad sunburn/patchy plumage/scabby scales",
        "Very pale/Bleach white plumage/slightly translucent scales",
        "Amazing tan/colorful plumage/colorful scales",
        "Thick",
        "Hunched over"
    ],
    "statement_piece": ["Strawhat", "Scarf", "Cloak"],
    "interests": [
        "Theater",
        "Revelry",
        "Playing",
        "Writing & Reading",
        "Sports",
        "Painting",
        "Food",
        "Love",
        "Pranks",
        "Wisdom",
        "Fighting",
        "Outdoors",
        "Traveling",
        "Stories",
        "Helping",
        "Wealth and Baubles",
        "Ambivalence",
        "Conversation and Friendship",
        "Double interest"
    ],
    "fighting_style": [
        "Traveler",
        "Sea-farer",
        "Brawler",
        "Wrestler",
        "Monk",
        "Pugilist",
        "Archer",
        "Minstrel",
        "Officer",
        "Rogue",
        "Knife Thrower",
        "Duelist",
        "Knight",
        "Paladin",
        "Berserker",
        "Slayer",
        "Peltast",
        "Hoplite",
        "Hunter",
        "Coastie",
        "Swordfighter"
    ]
}
